query($mod :String!, $id :String!) {
  blocks(mod: $mod, id:$id) {
    mod
    id
    name
    changed_at
    introduced_at
    meta{
      key
      technical
      values{
        value
        mask
      }
    }
    flags{
      physics
      inventory_slots
      editors
    }
    
  }
}