type Mutation {

  storeItem(data: InputItem!): Item
  deleteItem(mod: String!, id: String!): Item

  storeEnchantment(newData: InputEnchantment!): Enchantment
  deleteEnchantment(mod: String!, id: String!): Enchantment

  # storeEntity(newData: InputEntity!): Entity
  # deleteEntity(mod: String!, id: String!): Entity

  # storeStatusEffect(newData: InputStatusEffect!): StatusEffect
  # deleteStatusEffect(mod: String!, id: String!): StatusEffect

}