
input OldId{
  mod:String!
  id:String!
}

input InputItem {
  # Metadata settings
  meta: [InputMeta]
  flags: InputItemFlags

  # Mod this object comes from
  mod: String!

  # Id of this object, combined with mod in format mod:id
  id: String!

  # English name of object
  name: String!

  # Version this object first appeared in
  introduced_at: String!

  # Last Version this object was edited
  changed_at: String!
}

input InputItemFlags {
  # Amount of damage
  durability: Int

  # Item can be coloured
  dyeable: Boolean

  # Can be smashed in an anvil to fix it.
  repairable: Boolean

  # valid enchantments for this item
  #enchantments: [InputEnchantment!]

  # Editors to use for this objects NBT data.
  editors: [NBTEditors!]
}

input InputBlock {
  # Metadata settings
  #meta: [Meta]
  #flags: ItemFlags

  # Mod this object comes from
  mod: String!

  # Id of this object, combined with mod in format mod:id
  id: String!

  # English name of object
  name: String!

  # Version this object first appeared in
  introduced_at: String!

  # Last Version this object was edited
  changed_at: String!
  
  #Is block a technical one
  technical: Boolean

  meta: [InputMeta]
  flags: InputBlockFlags

}

input InputMeta {
  key: String
  values: [InputMetaEntry]
  technical: Boolean
}

input InputMetaEntry {
  value: String
  technical: Boolean
  mask: Int
}

input InputBlockFlags {
  # Does this block obey physics (sand/gravel/anvil)
  physics: Boolean

  # Resistance to explosions
  hardness: Int

  # Does this block prevent piston movement
  unpushable: Boolean

  # Is this block transparent (no suffocate damage)
  transparent: Boolean
  # Light values for this block 
  light: InputBlockFlagsLight

  #Number of inventory slots this block can hold
  inventory_slots: Int

  editors: [NBTEditors!]
}

input InputBlockFlagsLight {
  # Amount of light emitted by block
  emit: Int

  # Amount of light that is dropped as it passes through this block
  decay: Int
}

input InputEnchantment {
  # Numeric id
  num_id: Int!

  # Max level
  level: Int!

  # Mod this object comes from
  mod: String!

  # Id of this object, combined with mod in format mod:id
  id: String!

  # English name of object
  name: String!

  # Version this object first appeared in
  introduced_at: String!

  # Last Version this object was edited
  changed_at: String!
}

input InputEntity {
  # Mod this object comes from
  mod: String!

  # Id of this object, combined with mod in format mod:id
  id: String!

  # English name of object
  name: String!

  # Version this object first appeared in
  introduced_at: String!

  # Last Version this object was edited
  changed_at: String!
}



input InputStatusEffect {
  
  # Mod this object comes from
  mod: String!

  # Id of this object, combined with mod in format mod:id
  id: String!

  #Old ID
  num_id: Int!

  # English name of object
  name: String!

  # Version this object first appeared in
  introduced_at: String!

  # Last Version this object was edited
  changed_at: String!
}

type mutation {
  addItem(newData: InputItem!): Item
  updateItem(oldId: OldId!, newData: InputItem!): Item
  deleteItem(oldId: OldId!): Item

  addBlock(newData: InputBlock!): Block
  updateBlock(oldId: OldId!, newData: InputBlock!): Block
  deleteBlock(oldId: OldId!): Block

  addEnchantment(newData: InputEnchantment!): Enchantment
  updateEnchantment(oldId: OldId!, newData: InputEnchantment!): Enchantment
  deleteEnchantment(oldId: OldId!): Enchantment

  addEntity(newData: InputEntity!): Entity
  updateEntity(oldId: OldId!, newData: InputEntity!): Entity
  deleteEntity(oldId: OldId!): Entity

  addStatusEffect(newData: InputStatusEffect!): StatusEffect
  updateStatusEffect(oldId: OldId!, newData: InputStatusEffect!): StatusEffect
  deleteStatusEffect(oldId: OldId!): StatusEffect

}