query($mod :String!, $id :String!) {
  data: items(mod: $mod, id:$id) {
    mod
    id
    name
    changed_at
    introduced_at
    technical
    meta{
      key
      technical
      values{
        value
        mask
      }
    }
    variants{
      label
      value
    }
    flags{
      isBlock
      durability
      dyeable
      repairable
      enchantments { id }
      editors
      physics
      hardness
      unpushable
      transparent
      #light: InputBlockFlagsLight
      inventory{
        slots
        type
      }
    }

    
  }
}