query($mod :String!, $id :String!) {
  data: items(mod: $mod, id:$id) {
    mod
    id
    name
    changed_at
    introduced_at
    meta{
      key
      technical
      values{
        value
        mask
      }
    }
    flags{
      durability
      dyeable
      repairable
      enchantments { id }
      editors
    }

    
  }
}