type Block {
  # Metadata settings
  meta: [Meta!]
  flags: BlockFlags

  # Mod this object comes from
  mod: String

  # Id of this object, combined with mod in format mod:id
  id(
    # Prefix with the mod field value in format mod:id
    prefixMod: Boolean = false
  ): String

  # English name of object
  name: String

  # Version this object first appeared in
  introduced_at: String

  # Last Version this object was edited
  changed_at: String
}

type BlockFlags {
  # Does this block obey physics (sand/gravel/anvil)
  physics: Boolean

  # Resistance to explosions
  hardness: Int

  # Does this block prevent piston movement
  unpushable: Boolean

  # Is this block transparent (no suffocate damage)
  transparent: Boolean
  # Light data
  light: BlockFlagsLight

  #Number of slots
  inventory_slots: Int

  # Editors to use for this objects NBT data.
  editors: [NBTEditors!]
}

type BlockFlagsLight {
  # Amount of light emitted by block
  emit: Int

  # Amount of light that is dropped as it passes through this block
  decay: Int
}