

type Item {
  # Metadata settings
  meta: [Meta!]
  variants: [Variant!]

  flags: ItemFlags

  # Mod this object comes from
  mod: String

  # Id of this object, combined with mod in format mod:id
  id(
    # Prefix with the mod field value in format mod:id
    prefixMod: Boolean = false
  ): String

  # English name of object
  name: String

  # Version this object first appeared in
  introduced_at: String

  # Last Version this object was edited
  changed_at: String

  #Is this item a technical item (not normally accessed)
  technical: Boolean!
}

type Variant {
  label: String!
  value: Int!
}

type ItemFlags {

  # Is this item a block
  isBlock: Boolean!

  # Does this block obey physics (sand/gravel/anvil)
  physics: Boolean

  # Resistance to explosions
  hardness: Int

  # Does this block prevent piston movement
  unpushable: Boolean

  # Is this block transparent (no suffocate damage)
  transparent: Boolean
  # Light data
  light: BlockFlagsLight

  #Number of slots
  inventory_slots: Int
  
  # Amount of damage
  durability: Int

  # Item can be coloured
  dyeable: Boolean

  # Can be smashed in an anvil to fix it.
  repairable: Boolean

  # valid enchantments for this item
  enchantments: [Enchantment!]

  # Editors to use for this objects NBT data.
  editors: [NBTEditors!]
}

type BlockFlagsLight {
  # Amount of light emitted by block
  emit: Int

  # Amount of light that is dropped as it passes through this block
  decay: Int
}